[package]
name = "fixedbitset"
version = "0.0.1"
authors = ["bluss"]
license = "MIT/Apache-2.0"

description = "Simple BitSet type."
#documentation = ""
repository = "https://github.com/bluss/fixedbitset"

keywords = ["container", "data-structure", "bitvec", "bitset"]
